### ISSUE TITLE
Text extends outside the window

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#126]
v.1.1.0

<img width="383" alt="Screen Shot 2023-04-22 at 20 58 13" src="https://user-images.githubusercontent.com/62497891/233799696-6704530f-7d14-4669-b630-ac057589ae1b.png">

**Comment by ilyhalight** [comment]
Browser?
![image](https://user-images.githubusercontent.com/62353659/233810812-0ae05cde-90df-4018-877b-a23176f551c3.png)

**Comment by Oleg-Chashko** [comment]
@ilyhalight 
Google Chrome v.112.0.5615.137
macOS v.12.6.5 (21G531)

**Comment by ilyhalight** [comment]
> Google Chrome v.112.0.5615.137 macOS v.12.6.5 (21G531)

It looks like something specific only for MacOs, because everything works fine on Windows in Chrome. I doubt that it will be possible to fix it, because I don't have a device with MacOS, and the virtual machine (only MacOS) works with huge lags due to the Nvidia videocard. If one of the other users uses Mac OS, then he can try to fix it himself and send the change to the Pull Request.

**Comment by Oleg-Chashko** [comment]
In linux Fedora 38 the same issue.

<img width="1438" alt="Screen Shot 2023-04-26 at 21 16 41" src="https://user-images.githubusercontent.com/62497891/234667764-3897f498-b60f-4162-8368-6f5a9f9fab6c.png">

**Comment by Oleg-Chashko** [comment]
Since this problem does not only affect macOS. Would you be able to check and correct for this on a linux operating system?

**Comment by ilyhalight** [comment]
> Since this problem does not only affect macOS. Would you be able to check and correct for this on a linux operating system?

I'll check it out a little later

**Comment by ilyhalight** [comment]
Fixed in 1.1.2
