### ISSUE TITLE
Не работает Safari последней версии

### ISSUE THREAD

**Issue by bolkonskiy** [ilyhalight/voice-over-translation#351]
Добрый день! на сафари на OSX не работает, либо говорит "ошибка скрипта" либо висит восклицательный знак и перевод не включается.

<img width="792" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/42890450/ff52b32b-959c-4313-b0a7-77cfb3b155c2">

<img width="313" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/42890450/17fa5b13-1592-41e3-891a-5c684188fa1d">

кнопка не активна:
<img width="268" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/42890450/c143777b-daba-4bca-a987-25d6fd7d4c62">

**Comment by SashaXser** [comment]
> Добрый день! на сафари на OSX не работает, либо говорит "ошибка скрипта" либо висит восклицательный знак и перевод не включается.
> <img alt="image" width="792" src="https://user-images.githubusercontent.com/42890450/272193253-ff52b32b-959c-4313-b0a7-77cfb3b155c2.png"> <img alt="image" width="313" src="https://user-images.githubusercontent.com/42890450/272193514-17fa5b13-1592-41e3-891a-5c684188fa1d.png">
> 
> кнопка не активна: <img alt="image" width="268" src="https://user-images.githubusercontent.com/42890450/272193714-c143777b-daba-4bca-a987-25d6fd7d4c62.png">

Установи бету версию и проверь работу

**Comment by lavaw** [comment]
у меня тоже ошибка, пишет не удалось получить данные необходимые для перевода

**Comment by SashaXser** [comment]
> у меня тоже ошибка, пишет не удалось получить данные необходимые для перевода

Покажи скрин ошибки и консоли

**Comment by lavaw** [comment]
> > у меня тоже ошибка, пиш
<img width="1440" alt="Снимок экрана 2023-10-03 в 18 33 20" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/1f9c121f-3340-4d8e-9cee-e1e1c40a33b9">
ет не удалось получить данные необходимые для перевода
> 
> Покажи скрин ошибки и консоли

**Comment by lavaw** [comment]
<img width="472" alt="Снимок экрана 2023-10-03 в 18 36 42" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/1a041fbb-b929-459c-ba77-638512b9322a">
вот так еще

**Comment by SashaXser** [comment]
> <img alt="Снимок экрана 2023-10-03 в 18 36 42" width="472" src="https://user-images.githubusercontent.com/35728087/272317648-1a041fbb-b929-459c-ba77-638512b9322a.png"> вот так еще

Эта ошибка везде или только на Udemy?

**Comment by lavaw** [comment]
> > <img alt="Снимок экрана 2023-10-03 в 18 36 42" width="472" src="https://user-images.githubusercontent.com/35728087/272317648-1a041fbb-b929-459c-ba77-638512b9322a.png"> вот так еще
> 
> Эта ошибка везде или только на Udemy?

везде, но мне только для юдеми надо

**Comment by lavaw** [comment]
не нашел ответа в ветке

**Comment by lavaw** [comment]
<img width="1438" alt="Снимок экрана 2023-10-03 в 18 47 49" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/7103c439-69d3-4516-bdb5-96eb4190593d">

**Comment by SashaXser** [comment]
> <img alt="Снимок экрана 2023-10-03 в 18 47 49" width="1438" src="https://user-images.githubusercontent.com/35728087/272320917-7103c439-69d3-4516-bdb5-96eb4190593d.png">

Хм, тут все нормально. Вы пытаетесь перевести платный курс? Вы вставили токен в меню?

**Comment by lavaw** [comment]
да, платный курс, конечно вставил)

**Comment by SashaXser** [comment]
> да, платный курс, конечно вставил)

Можешь показать скриншот из вкладки "Сеть"? Именно с момента нажатия на кнопку перевода.

**Comment by lavaw** [comment]
<img width="1439" alt="Снимок экрана 2023-10-03 в 19 11 36" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/f6b94654-9ed2-4098-9f23-2b79bad44610">
<img width="1435" alt="Снимок экрана 2023-10-03 в 19 11 26" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/31cf1a55-0525-444b-8f85-caf25aec65c4">
<img width="1433" alt="Снимок экрана 2023-10-03 в 19 11 12" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/51eb4082-b3a4-4baf-ac6a-b82c836782ef">

**Comment by SashaXser** [comment]
> <img alt="Снимок экрана 2023-10-03 в 19 11 36" width="1439" src="https://user-images.githubusercontent.com/35728087/272328850-f6b94654-9ed2-4098-9f23-2b79bad44610.png"> <img alt="Снимок экрана 2023-10-03 в 19 11 26" width="1435" src="https://user-images.githubusercontent.com/35728087/272328881-31cf1a55-0525-444b-8f85-caf25aec65c4.png"> <img alt="Снимок экрана 2023-10-03 в 19 11 12" width="1433" src="https://user-images.githubusercontent.com/35728087/272328893-51eb4082-b3a4-4baf-ac6a-b82c836782ef.png">

Во, какой ответ у запроса где me?

**Comment by lavaw** [comment]
:status: 200
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Expose-Headers: Authorization
allow: GET, HEAD, OPTIONS
Cache-Control: max-age=300, private
cf-cache-status: DYNAMIC
cf-ray: 81067f5adcd19db0-DME
Content-Encoding: br
Content-Type: application/json
Date: Tue, 03 Oct 2023 16:17:49 GMT
ETag: W/"fb7ed34ac31995cf243895be95381088"
Referrer-Policy: strict-origin-when-cross-origin
Server: cloudflare
Set-Cookie: evi="3@N2Qbt2vXA0biS6XHnEJt-osHRxPaASnm3EdpEobjaqlqtemAp59RUikvxB7bAaC7ItQITB2Lrh_gy4xNjSFH7NFajGX_rwEeLvk="; expires=Thu, 02 Nov 2023 16:17:49 GMT; Max-Age=2592000; Path=/
Set-Cookie: eva=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: __udmy_evid=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: udmy_branded_partner=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: exaff=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: inaff=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: __udmy_2_v57r=277c085bb37b4db690faafa124a0ebbc; Domain=.udemy.com; expires=Wed, 02 Oct 2024 16:17:49 GMT; Max-Age=31536000; Path=/; Secure
Set-Cookie: ud_rule_vars=eJxtjtFqAyEQRX9l8bXNMjO6cfVbFmR0NZWmlaqbl5B_70ISKDSvwz3nzFV0rqfY4-ouueVeqiWtA8yT91J7tfqjgcScGEkxRO-DDaV85ijsIK6LSLm2fmfdyj0u-30RBCQPCAegAdESWaQR1YzSvAFYgEW876sz72gvW_hwvXJKObhWthqiu3DN7M8PW6kn_s7hD1Tjzxbby6Ic8GhRW2XGSZKk_8WwN1p8_Nzz1wvDZHG2MI2gzGz003ATt1-kWFrD:1qni5l:tYVdMbZR32YDENHj_5ZrkTM9lZQ; expires=Thu, 02 Oct 2025 16:17:49 GMT; Max-Age=63072000; Path=/
Set-Cookie: ud_cache_brand=RUru_RU; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_marketplace_country=RU; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_price_country=NL; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_release=7bf397cea68385fc0cd2; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_user=247641102; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_version=1; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_language=ru; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_device=None; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_logged_in=1; expires=Wed, 04 Oct 2023 16:17:49 GMT; Max-Age=86400; Path=/; Secure
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin, X-Udemy-Cache-Brand, X-Udemy-Cache-Campaign-Code, X-Udemy-Cache-Price-Country, X-Udemy-Cache-Release, X-Udemy-Cache-User, X-Udemy-Cache-Version, Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
x-permitted-cross-domain-policies: master-only
x-udemy-cache-app-namespace
X-XSS-Protection: 1; mode=block

**Comment by lavaw** [comment]
это?
:status: 200
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Expose-Headers: Authorization
allow: GET, HEAD, OPTIONS
Cache-Control: max-age=0, max-stale=0, must-revalidate, no-cache, no-store, post-check=0, pre-check=0, private
cf-cache-status: DYNAMIC
cf-ray: 81068692bfb59db0-DME
Content-Encoding: br
Content-Type: application/json
Date: Tue, 03 Oct 2023 16:22:45 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: cloudflare
Set-Cookie: evi="3@IIDfN_89_9323geTGKexkeB-9FbW1klR2nHOEDUqCrZ0nA0zRN_oq5uyUkQXXBhiTLGTMN-KNGlzy_AroKlYVUPdVK-USE2tK8U="; expires=Thu, 02 Nov 2023 16:22:45 GMT; Max-Age=2592000; Path=/
Set-Cookie: eva=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: __udmy_evid=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: udmy_branded_partner=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: exaff=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: inaff=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/
Set-Cookie: __udmy_2_v57r=277c085bb37b4db690faafa124a0ebbc; Domain=.udemy.com; expires=Wed, 02 Oct 2024 16:22:45 GMT; Max-Age=31536000; Path=/; Secure
Set-Cookie: ud_rule_vars="eJxtjkFuwyAQRa9isW1jzWCIgbNYQgMeUtQ0qICziXL3umoqVWq2o__em5voVE_cefXX3HIv1cl5jmB0CNMc1BqOFhJRIpSKgEOILpbynlm4QdwWkXJt_Yf1K3Ve9vsiJMjpgHAAOSA6KR3KEZXByb4AOIBFvO6rM-1oL1t8871SSjn6VrYa2V-pZgrnh63UE11y_ANV_ty4PS1OAx6_i0qPaNAq_a8Y90bjx889fzwxaIfGgR5BWWPnX8Nd3L8Aouhavw==:1qniAX:mra3J9-EtODX3oyREtfDtMeR5pg"; expires=Thu, 02 Oct 2025 16:22:45 GMT; Max-Age=63072000; Path=/
Set-Cookie: ud_cache_brand=RUru_RU; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_marketplace_country=RU; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_price_country=NL; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_release=7bf397cea68385fc0cd2; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_user=247641102; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_version=1; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_language=ru; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_device=None; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Set-Cookie: ud_cache_logged_in=1; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin, Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
x-permitted-cross-domain-policies: master-only
x-udemy-cache-app-namespace
X-XSS-Protection: 1; mode=block

**Comment by SashaXser** [comment]
> это? :status: 200 Access-Control-Allow-Credentials: true Access-Control-Allow-Headers: Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS Access-Control-Expose-Headers: Authorization allow: GET, HEAD, OPTIONS Cache-Control: max-age=0, max-stale=0, must-revalidate, no-cache, no-store, post-check=0, pre-check=0, private cf-cache-status: DYNAMIC cf-ray: 81068692bfb59db0-DME Content-Encoding: br Content-Type: application/json Date: Tue, 03 Oct 2023 16:22:45 GMT Referrer-Policy: strict-origin-when-cross-origin Server: cloudflare Set-Cookie: evi="3@IIDfN_89_9323geTGKexkeB-9FbW1klR2nHOEDUqCrZ0nA0zRN_oq5uyUkQXXBhiTLGTMN-KNGlzy_AroKlYVUPdVK-USE2tK8U="; expires=Thu, 02 Nov 2023 16:22:45 GMT; Max-Age=2592000; Path=/ Set-Cookie: eva=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/ Set-Cookie: __udmy_evid=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/ Set-Cookie: udmy_branded_partner=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/ Set-Cookie: exaff=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/ Set-Cookie: inaff=""; expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0; Path=/ Set-Cookie: __udmy_2_v57r=277c085bb37b4db690faafa124a0ebbc; Domain=.udemy.com; expires=Wed, 02 Oct 2024 16:22:45 GMT; Max-Age=31536000; Path=/; Secure Set-Cookie: ud_rule_vars="eJxtjkFuwyAQRa9isW1jzWCIgbNYQgMeUtQ0qICziXL3umoqVWq2o__em5voVE_cefXX3HIv1cl5jmB0CNMc1BqOFhJRIpSKgEOILpbynlm4QdwWkXJt_Yf1K3Ve9vsiJMjpgHAAOSA6KR3KEZXByb4AOIBFvO6rM-1oL1t8871SSjn6VrYa2V-pZgrnh63UE11y_ANV_ty4PS1OAx6_i0qPaNAq_a8Y90bjx889fzwxaIfGgR5BWWPnX8Nd3L8Aouhavw==:1qniAX:mra3J9-EtODX3oyREtfDtMeR5pg"; expires=Thu, 02 Oct 2025 16:22:45 GMT; Max-Age=63072000; Path=/ Set-Cookie: ud_cache_brand=RUru_RU; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_marketplace_country=RU; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_price_country=NL; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_release=7bf397cea68385fc0cd2; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_user=247641102; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_version=1; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_language=ru; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_device=None; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Set-Cookie: ud_cache_logged_in=1; expires=Wed, 04 Oct 2023 16:22:45 GMT; Max-Age=86400; Path=/; Secure Strict-Transport-Security: max-age=31536000; includeSubDomains Vary: Origin, Accept-Encoding X-Content-Type-Options: nosniff X-Frame-Options: SAMEORIGIN x-permitted-cross-domain-policies: master-only x-udemy-cache-app-namespace X-XSS-Protection: 1; mode=block

Это заголовки, мне нужен именно ответ.

**Comment by lavaw** [comment]
если это надо смотреть во вкладке предпросмотр, то там пусто

**Comment by SashaXser** [comment]
> если это надо смотреть во вкладке предпросмотр, то там пусто

Вот поэтому и не работает) Субтитров то нету

**Comment by lavaw** [comment]
> > если это надо смотреть во вкладке предпросмотр, то там пусто
> 
> Вот поэтому и не работает) Субтитров то нету

и как быть?)

**Comment by lavaw** [comment]
<img width="1434" alt="Снимок экрана 2023-10-03 в 19 37 23" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/a2d018af-a17e-48a8-a9ed-906e30047c4a">

**Comment by MrSoczekXD** [comment]
> > > у меня тоже ошибка, пиш
> 
> <img alt="Снимок экрана 2023-10-03 в 18 33 20" width="1440" src="https://user-images.githubusercontent.com/35728087/272317108-1f9c121f-3340-4d8e-9cee-e1e1c40a33b9.png"> ет не удалось получить данные необходимые для перевода > > Покажи скрин ошибки и консоли

@ilyhalight safari не поддерживает [requestIdleCallback](https://github.com/ilyhalight/voice-over-translation/blob/2743fd566db910f853116041e3e4b7d1651e80fe/src/utils/VideoObserver.js#L26). Добавь [polyfill](https://github.com/pladaria/requestidlecallback-polyfill)

**Comment by SashaXser** [comment]
> > > > у меня тоже ошибка, пиш
> > 
> > 
> > <img alt="Снимок экрана 2023-10-03 в 18 33 20" width="1440" src="https://user-images.githubusercontent.com/35728087/272317108-1f9c121f-3340-4d8e-9cee-e1e1c40a33b9.png"> ет не удалось получить данные необходимые для перевода > > Покажи скрин ошибки и консоли
> 
> @ilyhalight safari не поддерживает [requestIdleCallback](https://github.com/ilyhalight/voice-over-translation/blob/2743fd566db910f853116041e3e4b7d1651e80fe/src/utils/VideoObserver.js#L26). Добавь [polyfill](https://github.com/pladaria/requestidlecallback-polyfill)

Предлагаю сделать так:

```
win.requestIdleCallback = win.requestIdleCallback || (cb => setTimeout(cb, 1));
win.cancelIdleCallback = win.cancelIdleCallback || (id => clearTimeout(id));
```

**Comment by MrSoczekXD** [comment]
> > > > > у меня тоже ошибка, пиш
> > > 
> > > 
> > > <img alt="Снимок экрана 2023-10-03 в 18 33 20" width="1440" src="https://user-images.githubusercontent.com/35728087/272317108-1f9c121f-3340-4d8e-9cee-e1e1c40a33b9.png"> ет не удалось получить данные необходимые для перевода > > Покажи скрин ошибки и консоли
> > 
> > 
> > @ilyhalight safari не поддерживает [requestIdleCallback](https://github.com/ilyhalight/voice-over-translation/blob/2743fd566db910f853116041e3e4b7d1651e80fe/src/utils/VideoObserver.js#L26). Добавь [polyfill](https://github.com/pladaria/requestidlecallback-polyfill)
> 
> Предлагаю сделать так:
> 
> ```
> win.requestIdleCallback = win.requestIdleCallback || (cb => setTimeout(cb, 1));
> win.cancelIdleCallback = win.cancelIdleCallback || (id => clearTimeout(id));
> ```

В `cb` должен передаваться [IdleDeadline](https://developer.mozilla.org/en-US/docs/Web/API/IdleDeadline)

**Comment by SashaXser** [comment]
> > > > > > у меня тоже ошибка, пиш
> > > > 
> > > > 
> > > > <img alt="Снимок экрана 2023-10-03 в 18 33 20" width="1440" src="https://user-images.githubusercontent.com/35728087/272317108-1f9c121f-3340-4d8e-9cee-e1e1c40a33b9.png"> ет не удалось получить данные необходимые для перевода > > Покажи скрин ошибки и консоли
> > > 
> > > 
> > > @ilyhalight safari не поддерживает [requestIdleCallback](https://github.com/ilyhalight/voice-over-translation/blob/2743fd566db910f853116041e3e4b7d1651e80fe/src/utils/VideoObserver.js#L26). Добавь [polyfill](https://github.com/pladaria/requestidlecallback-polyfill)
> > 
> > 
> > Предлагаю сделать так:
> > ```
> > win.requestIdleCallback = win.requestIdleCallback || (cb => setTimeout(cb, 1));
> > win.cancelIdleCallback = win.cancelIdleCallback || (id => clearTimeout(id));
> > ```
> 
> В `cb` должен передаваться [IdleDeadline](https://developer.mozilla.org/en-US/docs/Web/API/IdleDeadline)

Не ну по факту safari для нищих))
```
export {
	win as window,
	doc as document,
	requestAnimationFrame, cancelAnimationFrame,
	requestIdleCallback, cancelIdleCallback
};

/**
 * Get global object
 * @returns {object} window object
 * @private
 */
function getGlobal() {
	return (typeof globalThis === "object" && globalThis !== null && globalThis.Object === Object && globalThis) ||
		(typeof global === "object" && global !== null && global.Object === Object && global) ||
		(typeof self === "object" && self !== null && self.Object === Object && self) ||
		Function("return this")();
}

/**
 * Get fallback object
 * @param {object} w global object
 * @returns {Array} fallback object array
 * @private
 */
function getFallback(w) {
	const hasRAF = typeof w?.requestAnimationFrame === "function";
	const hasRIC = typeof w?.requestIdleCallback === "function";

	return [
		hasRAF ? w.requestAnimationFrame : (cb => setTimeout(cb, 1)),
		hasRAF ? w.cancelAnimationFrame : (id => clearTimeout(id)),
		hasRIC ? w.requestIdleCallback : requestAnimationFrame,
		hasRIC ? w.cancelIdleCallback : cancelAnimationFrame
	];
}

const win = getGlobal();
const doc = win?.document;

const [
	requestAnimationFrame,
	cancelAnimationFrame,
	requestIdleCallback,
	cancelIdleCallback
] = getFallback(win);
```

**Comment by ilyhalight** [comment]
Попробуйте обновиться до последней беты, должно работать

**Comment by lavaw** [comment]
> Попробуйте обновиться до последней беты, должно работать

а где ее найти?

**Comment by ilyhalight** [comment]
> > Попробуйте обновиться до последней беты, должно работать
> 
> а где ее найти?

https://github.com/ilyhalight/voice-over-translation/releases и там внизу выбираете нужный файл

**Comment by lavaw** [comment]
<img width="491" alt="Снимок экрана 2023-10-07 в 18 57 05" src="https://github.com/ilyhalight/voice-over-translation/assets/35728087/b7b131ba-381d-4380-b7cf-dbc67ca50fc1">
вот такая ошибка, а перед этим говорит что перевод может занять около минуты


> > > Попробуйте обновиться до последней беты, должно работать
> > 
> > 
> > а где ее найти?
> 
> https://github.com/ilyhalight/voice-over-translation/releases и там внизу выбираете нужный файл
